version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7

workflows:
  testing:
    jobs:
      - runner-test
jobs:
  runner-test:
    machine: true
    resource_class: bgmorton/runner-test
    steps:
      - run: echo "Hi I'm on Runners!"
      # - node/test:
      #   # This is the node version to use for the `cimg/node` tag
      #   # Relevant tags can be found on the CircleCI Developer Hub
      #   # https://circleci.com/developer/images/image/cimg/node
      #   version: '16.10'
      #   # If you are using yarn, change the line below from "npm" to "yarn"
      #   pkg-manager: npm
