version: 2.1

orbs:
  node: circleci/node@5.0.2

workflows:
  testing:
    jobs:
      - runner-test

jobs:
  runner-test:
    machine: true
    resource_class: bgmorton/runner-test
    steps:
      - run: echo "Hi I'm on Runners!"
      - run: node --version
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Test app
     
     
 
